title: Supplychainpy Python library for supply chain analysis
description: "Blog for supplychainpy"
baseurl: ""
url: "/supplychainpy/github.io"
comments: true
paginate: 10
paginate_path: "/posts/:num"
image_path:
highlighter: 'rouge'


markdown: kramdown