title: Supplychainpy Python library for supply chain analysis
description: "Blog for supplychainpy"
baseurl: ""
url: ""
comments: true
image_path:
highlighter: 'rouge'
markdown: kramdown
paginate: 4
paginate_path: '/blog/page:num/'
gems: [jekyll-paginate, jekyll-feed]

